PHCLT/PHCLT/Controllers/SubjectMasterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PHCLT.Controllers
{
    public class SubjectMasterController : Controller
    {
        // GET: SubjectMaster
        ClsSystem ob = new ClsSystem();
        public ActionResult Index()
        {
            List<standermaster> Standermaster = new List<standermaster>();
            
            var phcList = GetstanderList();
            ViewBag.standerList = phcList;
            return View();
        }
        private List<standermaster> GetstanderList()
        {
            List<standermaster> stdMasters = new List<standermaster>();
            DataTable dt = ob.Returntable("select * from StdMaster order by id");
            for (int i = 0; i <= dt.Rows.Count - 1; i++)
            {
                standermaster distMaster = new standermaster
                {
                    id = (int)dt.Rows[i]["id"],
                    Stdname = dt.Rows[i]["Stdname"].ToString()
               
                };
                stdMasters.Add(distMaster);
            }
            return stdMasters;
        }
        public class standermaster
        {
            public int id { get; set; }
            public string Stdname { get; set; }
        }
        public class Resultpass<T>
        {
            public bool opstatus { get; set; }
            public string opmessage { get; set; }
        }
        [HttpPost]
        public JsonResult Addsubject(string subjectname, string stdname)
        {
            Resultpass<object> result = new Resultpass<object>();
            try
            {


                string billno = ob.FindOneString("select isnull(max(Id),0)+1 from SubjectMaster");
                ob.excute("insert into SubjectMaster(Id, SubjectName, STD,Isdelete) values(" + billno + ",'" + subjectname + "','" + stdname + "',0)");
                result.opstatus = true;
                result.opmessage = "0";
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public ActionResult SubjectMasterList()
        {
            List<subjectmaster> distMasters = Getsubjectmaster();
            ViewBag.PHCdetailList = distMasters;
            return View();
        }
        private List<subjectmaster> Getsubjectmaster()
        {
            List<subjectmaster> distMasters = new List<subjectmaster>();
            DataTable dt = ob.Returntable("select * from SubjectMaster where Isdelete=0 order by id");
            for (int i = 0; i <= dt.Rows.Count - 1; i++)
            {
                subjectmaster distMaster = new subjectmaster
                {
                    id = (int)dt.Rows[i]["id"],
                    STD = dt.Rows[i]["STD"].ToString(),
                    SubjectName = dt.Rows[i]["SubjectName"].ToString()
                };
                distMasters.Add(distMaster);
            }
            return distMasters;
        }
        public class subjectmaster
        {
            public int id { get; set; }
            public string STD { get; set; }
            public string SubjectName { get; set; }

        }

        [HttpPost]
        public JsonResult DeleteId(string id)
        {
            
            ob.excute("update SubjectMaster set Isdelete=1 where id=" + Convert.ToInt32(id.ToString()) + "");

            return Json("Save", JsonRequestBehavior.AllowGet);
        }

    }
}

PHCLT/PHCLT/Views/SubjectMaster/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Subject Master</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    
                        <div class="card-body">
                            <div class="form-group">
                                <label for="cmbrPHCCenter">Standard</label>
                                <select class="form-control select2" id="Standard"  style="width: 100%;">
                                    <option selected="selected" value="0">Select a Standard</option>

                                    @foreach (var phc in ViewBag.standerList)
                                    {
                                        <option value="@phc.id">@phc.Stdname</option>
                                    }
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Subject Name</label>
                                <input type="text" class="form-control" id="subjectname" placeholder="Enter Subject Name">
                            </div>
                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="button" id="btnsave" class="btn btn-primary">Save</button>
                            <button type="button" id="btnviewlist" class="btn btn-primary">View List</button>
                        </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- AdminLTE -->
<script src="~/dist/js/adminlte.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="~/dist/js/demo.js"></script>
<!-- Bootstrap 4 -->
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Select2 -->
<script src="~/plugins/select2/js/select2.full.min.js"></script>
<!-- InputMask -->
<script src="~/plugins/moment/moment.min.js"></script>
<script src="~/plugins/inputmask/jquery.inputmask.min.js"></script>
<!-- date-range-picker -->
<script src="~/plugins/daterangepicker/daterangepicker.js"></script>
<!-- AdminLTE App -->
<script src="~/dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="~/plugins/sweetalert2/sweetalert2.min.js"></script>
<!-- Toastr -->
<script src="~/plugins/toastr/toastr.min.js"></script>
<!-- date-range-picker -->
<script src="~/Scripts/SubjectMaster/Subjectmaster.js"></script>

PHCLT/PHCLT/Views/SubjectMaster/SubjectMasterList.cshtml
@{
    ViewBag.Title = "SubjectMasterList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome Icons -->
<!-- IonIcons -->
<link href="~/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

<!-- Theme style -->
<link href="~/dist/css/adminlte.min.css" rel="stylesheet" />

<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome -->
<link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
<!-- daterange picker -->
<link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
<!-- Bootstrap Color Picker -->
<link rel="stylesheet" href="~/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css">
<!-- Tempusdominus Bootstrap 4 -->
<link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
<!-- Select2 -->
<link rel="stylesheet" href="~/plugins/select2/css/select2.min.css">
<link rel="stylesheet" href="~/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
<!-- Bootstrap4 Duallistbox -->
<link rel="stylesheet" href="~/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css">
<!-- BS Stepper -->
<link rel="stylesheet" href="~/plugins/bs-stepper/css/bs-stepper.min.css">
<!-- dropzonejs -->
<link rel="stylesheet" href="~/plugins/dropzone/min/dropzone.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="~/dist/css/adminlte.min.css">
<link href="~/css/loader.css" rel="stylesheet" />
<link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
<style>
    #example1 th:nth-child(4),
    #example1 td:nth-child(4) {
        display: none;
    }
</style>
<div class="card-header row">
  
    <div class="col-md-6 d-flex align-items-center justify-content-end">
        <button type="button" class="btn btn-light" onclick="location.href='@Url.Action("Index","SubjectMaster")'">Add New Subject</button>
        <button type="button" class="btn btn-light" onclick="location.href='@Url.Action("NewDashboard","Home")'">Home</button>

    </div>
</div>
<div class="card-body">
    <table id="example1" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Standard</th>
                <th>Subject Name</th>
                <th>Action</th>
               
            </tr>
        </thead>
        <tbody>
            @foreach (var distMaster in ViewBag.PHCdetailList)
            {
            <tr>
                <td>@distMaster.STD</td>
                <td>@distMaster.SubjectName</td>
                <td><a class="btn btn-xs btn-danger" id="btndelete" onclick="deletedesignation('@distMaster.id')"><i class="fa fa-trash"></i></a></td>
                
            </tr>
            }
        </tbody>
    </table>
</div>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="~/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE -->
<script src="~/dist/js/adminlte.js"></script>
<!-- OPTIONAL SCRIPTS -->
<script src="~/plugins/chart.js/Chart.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="~/dist/js/demo.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="~/dist/js/pages/dashboard3.js"></script>
<!-- Bootstrap 4 -->
<script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Select2 -->
<script src="~/plugins/select2/js/select2.full.min.js"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="~/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js"></script>
<!-- InputMask -->
<script src="~/plugins/moment/moment.min.js"></script>
<script src="~/plugins/inputmask/jquery.inputmask.min.js"></script>
<!-- date-range-picker -->
<script src="~/plugins/daterangepicker/daterangepicker.js"></script>
<!-- bootstrap color picker -->
<script src="~/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Bootstrap Switch -->
<script src="~/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
<!-- BS-Stepper -->
<script src="~/plugins/bs-stepper/js/bs-stepper.min.js"></script>
<!-- dropzonejs -->
<script src="~/plugins/dropzone/min/dropzone.min.js"></script>
<!-- AdminLTE App -->
<script src="~/dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="~/dist/js/demo.js"></script>
<script src="~/plugins/inputmask/inputmask.js"></script>
<script src="~/plugins/inputmask/jquery.inputmask.js"></script>

<script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="~/plugins/jszip/jszip.min.js"></script>
<script src="~/plugins/pdfmake/pdfmake.min.js"></script>
<script src="~/plugins/pdfmake/vfs_fonts.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="~/Scripts/PHCdetail/PHCdetailList.js"></script>
<script>
    function deletedesignation(Id) {
        Swal.fire({
            title: "Are you sure?",
            text: "You won't be able to revert this!",
            icon: "warning",
            showCancelButton: true,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Yes, delete it!"
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: '/SubjectMaster/DeleteId?id=' + Id,
                    type: 'POST',
                    success: function (result) {
                        // Handle success
                        Swal.fire({
                            title: "Deleted!",
                            text: "Subject Has Been Deleted.",
                            icon: "success"
                        });
                        location.reload();
                    },
                    error: function (error) {
                        // Handle error
                        console.error('Error:', error.responseText);
                    }
                });

            }
        });
    }
</script>